name: Document Pull Request

on:
  workflow_call:
    secrets:
      CLIENT_ID:
        required: true
      PRIVATE_KEY:
        required: true

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  check-documentation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: aquaproj/aqua-installer@96a9bc20066c5bf5e275b41019cfc165b25f4e2e # v4.0.5
        with:
          aqua_version: v2.62.0

      - id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - run: github-comment exec -- github-comment hide
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Setup Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: '24'

      - name: Install markdownlint
        run: npm install -g markdownlint-cli2

      - name: Lint Markdown Files
        run: github-comment exec -k common-error -var env:Staging -var title:"Check Markdown Failed" -- markdownlint-cli2 "**/*.md" --config ".markdownlint.json"
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
